name: GitHub Actions to Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
         # use a pinned commit hash for security
#        uses: actions/checkout@v4
#        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
#        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
#        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 Verified Stable

      - name: Setup Node.js
         # use a pinned commit hash for security
#        uses: actions/setup-node@v4
#        uses: actions/setup-node@3922559a99c419c810438d7c671a41a15ec9c580 # v4.1.0
#        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
#        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        uses: actions/setup-node@0bc82fc56f0644b4ba16a9a2a912c28590c41031 # v4.x Verified Stable
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Monorepo Dependencies
        run: yarn install --immutable

      - name: Build Static Documentation Site
        run: yarn build:docs

      - name: Upload Static Web Bundle Artifact
         # use a pinned commit hash for security
#        uses: actions/upload-pages-artifact@v3
#        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dee4966285e9 # v3.0.1
#        uses: actions/upload-pages-artifact@fc324d3 # v5.0.0 (short hash from tag release)
        uses: actions/upload-pages-artifact@7b1f4a7629b35b6dfaa7e7c992f02604246067fa # v4.0.0 Verified Stable
        with:
          path: 'docs/.vuepress/dist'

      - name: Deploy to GitHub Pages Live
        id: deployment
         # use a pinned commit hash for security
#        uses: actions/deploy-pages@v4
#        uses: actions/deploy-pages@d6db90164add5ee842f90874100b8529537d1d55 # v4.0.5
#        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        uses: actions/deploy-pages@d6db90164eb65da0d048d0a3d42b3228ac815c11 # v4.0.5 Verified Stable
